#!/usr/bin/env python3
"""
test_spellwright_nemotron.py — Run spellwright with only Nemotron-3-Nano.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

# Override OLLAMA_HOST to skip Ollama
os.environ['OLLAMA_HOST'] = 'http://localhost:11435'  # not used

from spellwright import SPELL_PROMPTS, TASK_IDEAS, deepinfra_generate, validate_spell, craft_incantation, generate_spell_name
from grimoire import SpellBook
import json
import random
import time

GRIMOIRE = SpellBook()

def test_one():
    print("Testing spell generation with Nemotron-3-Nano-30B-A3B")
    
    # Pick random school and task
    school = random.choice(["cuda", "python", "shell"])
    task_desc = random.choice(TASK_IDEAS[school])
    
    print(f"School: {school}")
    print(f"Task: {task_desc}")
    
    # Build prompt
    prompt_template = SPELL_PROMPTS[school]
    prompt = prompt_template.format(task=task_desc)
    
    print("Generating...")
    content = deepinfra_generate(
        "nvidia/Nemotron-3-Nano-30B-A3B",
        prompt,
        temperature=0.7
    )
    
    if not content:
        print("Generation failed")
        return
    
    print(f"Raw length: {len(content)}")
    print("First 150 chars:")
    print(content[:150])
    
    # Validate
    is_valid, msg = validate_spell(school, content)
    if not is_valid:
        print(f"Validation failed: {msg}")
        # Try to extract code block
        import re
        if school in ["cuda", "python", "shell"] and "```" in content:
            blocks = re.findall(r'```(?:\w+)?\n(.*?)\n```', content, re.DOTALL)
            if blocks:
                content = blocks[0].strip()
                is_valid, msg = validate_spell(school, content)
                print(f"Extracted code block, new length: {len(content)}")
    
    if not is_valid:
        print(f"Still invalid: {msg}")
        return
    
    # Create spell metadata
    name = generate_spell_name(school, task_desc)
    incantation = craft_incantation(name, school)
    description = f"Auto-generated by Nemotron-3-Nano: {task_desc}"
    reagents = json.dumps(["deepinfra", "Nemotron-3-Nano-30B-A3B", "spellwright"])
    tags = f"auto-generated,{school},nemotron-nano"
    
    # Inscribe
    result = GRIMOIRE.inscribe(
        name=name,
        incantation=incantation,
        school=school,
        scroll=content,
        description=description,
        reagents=reagents,
        tags=tags,
        level=random.randint(1, 3)
    )
    
    print(f"✦ Inscribed: cast {incantation} [{school}]")
    print(f"  Name: {name}")
    print(f"  Size: {len(content)} chars")
    
    # Invoke to verify
    spell = GRIMOIRE.invoke(incantation, agent="test")
    if spell:
        print(f"✓ Invocation successful: {spell['name']}")
    else:
        print("✗ Invocation failed")

def main():
    print("═══ Spellwright Test (Nemotron‑3‑Nano) ⚒️ ═══")
    stats = GRIMOIRE.stats()
    print(f"Grimoire has {stats['total_spells']} spells")
    
    for i in range(3):
        print(f"\n--- Iteration {i+1} ---")
        test_one()
        time.sleep(2)
    
    stats = GRIMOIRE.stats()
    print(f"\nGrimoire now has {stats['total_spells']} spells")

if __name__ == "__main__":
    main()