/* FLUX Constraint Knowledge Base — Auto-generated by flux_sram_bake */
/* Cache-line aligned for zero-copy memory-mapped access */

#ifndef FLUX_KB_H
#define FLUX_KB_H
#include <stdint.h>

#define FLUX_KB_COUNT 7

typedef struct __attribute__((aligned(64))) {
    uint64_t fingerprint;
    uint64_t folded_hdc[2];
    uint32_t concept_id;
    uint32_t feature_mask;
    uint32_t flags;
    uint8_t padding[28];
} FluxKBRecord;

static inline float flux_kb_similarity(const FluxKBRecord* r, uint64_t q[2]) {
    int match = 0;
    match += __builtin_popcountll(~(r->folded_hdc[0] ^ q[0]));
    match += __builtin_popcountll(~(r->folded_hdc[1] ^ q[1]));
    return (float)match / 128.0f;
}

static inline const FluxKBRecord* flux_kb_query(const FluxKBRecord* kb,
    int n, uint64_t query[2], float threshold) {
    float best_sim = 0;
    const FluxKBRecord* best = 0;
    for (int i = 0; i < n; i++) {
        float sim = flux_kb_similarity(&kb[i], query);
        if (sim > best_sim) { best_sim = sim; best = &kb[i]; }
    }
    return (best_sim >= threshold) ? best : 0;
}

static const FluxKBRecord flux_kb[FLUX_KB_COUNT] = {
    {0xB314AE60CB741E69ULL, {0x43EF6F9ACBA599DAULL, 0x24037D53EA83B2F1ULL}, 0, 0x000004A5, 0x00000011},  /* temperature */
    {0xD0A708D7A9B0C252ULL, {0x748E249D210FCD88ULL, 0x96F87BAF639A0B90ULL}, 1, 0x000002A1, 0x00000011},  /* altitude */
    {0x1E8CBBA0EA346783ULL, {0x46810A1BA70F5D8FULL, 0x9D2E31E132940553ULL}, 2, 0x000004C1, 0x00000001},  /* airspeed */
    {0x3ED5792F787724FEULL, {0xCC74BDDBA8A0AB8DULL, 0x69C7476BD62C3B87ULL}, 3, 0x00000481, 0x00000001},  /* fuel_flow */
    {0x1EF0FCB31285911EULL, {0xBDD6DE051AC7FC41ULL, 0xB7B5FF06E58F9A01ULL}, 4, 0x00000485, 0x00000001},  /* oil_temp */
    {0x00EDCB8B6036AE9FULL, {0x265B6033C5633B34ULL, 0x139803D8B3FF3BE5ULL}, 5, 0x00000885, 0x00000001},  /* battery_v */
    {0xD3896B71F00394F7ULL, {0x265B6033C5633B34ULL, 0x139803D8B3FF3BE5ULL}, 6, 0x00000885, 0x00000001},  /* cabin_pressure */
};
#endif