#!/usr/bin/env python3
"""
flux_llvm_backend.py — FLUX Constraint → LLVM IR Compiler

The LLVM backend: compile once, target everything.
x86-64, AVX-512, Wasm, eBPF, RISC-V, ARM — all from one IR.

Usage:
    python3 flux_llvm_backend.py compile <file.guard> --target x86|avx512|wasm|ebpf|riscv
    python3 flux_llvm_backend.py ir <file.guard>          # Show LLVM IR
    python3 flux_llvm_backend.py bench <file.guard>       # Compile & benchmark
"""

import subprocess
import tempfile
import os
import sys
import ctypes
import time
import random
import struct

# ============================================================================
# GUARD Parser (shared with fluxc)
# ============================================================================

class Constraint:
    pass

class RangeConstraint(Constraint):
    def __init__(self, var, lo, hi):
        self.var = var
        self.lo = lo
        self.hi = hi
    def __repr__(self):
        return f"range({self.var}, {self.lo}, {self.hi})"

class DomainConstraint(Constraint):
    def __init__(self, var, mask):
        self.var = var
        self.mask = mask
    def __repr__(self):
        return f"domain({self.var}, 0x{self.mask:X})"

class AndConstraint(Constraint):
    def __init__(self, constraints):
        self.constraints = constraints
    def __repr__(self):
        return f"and({', '.join(str(c) for c in self.constraints)})"

def parse_guard(text):
    constraints = []
    for line in text.strip().split('\n'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if line.startswith('constraint '):
            line = line[len('constraint '):]
        if ' in [' in line and ']' in line:
            var = line.split(' in ')[0].strip()
            range_str = line.split(' in [')[1].split(']')[0]
            parts = range_str.split(',')
            lo = int(parts[0].strip())
            hi = int(parts[1].strip())
            constraints.append(RangeConstraint(var, lo, hi))
        elif ' in domain ' in line:
            var = line.split(' in domain ')[0].strip()
            mask = int(line.split(' in domain ')[1].strip(), 16)
            constraints.append(DomainConstraint(var, mask))
    if len(constraints) == 1:
        return constraints[0]
    return AndConstraint(constraints)


# ============================================================================
# LLVM IR Emitter
# ============================================================================

def emit_llvm_ir(constraint, func_name="flux_check", vectorize=False, width=16):
    """Emit LLVM IR for a constraint.
    
    Theorem 7 (DeepSeek): Pipeline correctness preserved through each stage.
    This emitter produces IR that LLVM then optimizes for the target.
    """
    lines = [
        '; FLUX Constraint → LLVM IR',
        '; Generated by flux_llvm_backend.py',
        ';',
        '; Optimization passes applied by LLVM:',
        ';   - dead constraint elimination (Theorem 5)',
        ';   - strength reduction (Theorem 6: range [0,2^k-1] → mask)',
        ';   - SIMD vectorization (Theorem 4: mask semantics preserved)',
        ';   - optimal instruction selection (Theorem 3)',
        '',
        'target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"',
        'target triple = "x86_64-pc-linux-gnu"',
        '',
    ]
    
    if vectorize:
        return emit_llvm_ir_vectorized(constraint, func_name, width)
    
    # Scalar function: (i32) -> i1
    lines.append(f'define i1 @{func_name}(i32 %val) {{')
    
    if isinstance(constraint, RangeConstraint):
        # Strength reduction: if lo=0, use unsigned comparison (1 cmp instead of 2)
        if constraint.lo == 0:
            lines.append(f'  ; Range [0, {constraint.hi}] → unsigned ≤ {constraint.hi}')
            lines.append(f'  %cmp = icmp ule i32 %val, {constraint.hi}')
            lines.append(f'  ret i1 %cmp')
        else:
            # General range: (unsigned)(val - lo) <= (hi - lo)
            lines.append(f'  ; Range [{constraint.lo}, {constraint.hi}] → subtraction trick')
            lines.append(f'  %off = sub i32 %val, {constraint.lo}')
            lines.append(f'  %span = sub i32 {constraint.hi}, {constraint.lo}')
            lines.append(f'  %cmp = icmp ule i32 %off, %span')
            lines.append(f'  ret i1 %cmp')
    
    elif isinstance(constraint, DomainConstraint):
        # (val & ~mask) == 0  ↔  (val & mask) == val
        complement = (~constraint.mask) & 0xFFFFFFFF
        lines.append(f'  ; Domain check: (val & 0x{constraint.mask:X}) == val')
        lines.append(f'  %masked = and i32 %val, {complement}')
        lines.append(f'  %cmp = icmp eq i32 %masked, 0')
        lines.append(f'  ret i1 %cmp')
    
    elif isinstance(constraint, AndConstraint):
        ranges = [c for c in constraint.constraints if isinstance(c, RangeConstraint)]
        domains = [c for c in constraint.constraints if isinstance(c, DomainConstraint)]
        
        # Dead constraint elimination (Theorem 5):
        # If domain mask ⊂ range bounds, range is dead
        for rc in ranges[:]:
            if rc.lo == 0:
                # Check if any domain mask implies this range
                for dc in domains:
                    if (dc.mask & rc.hi) == rc.hi:
                        ranges.remove(rc)
                        lines.append(f'  ; DEAD ELIMINATED: range [{rc.lo},{rc.hi}] subsumed by domain 0x{dc.mask:X}')
                        break
        
        result_var = 0
        for idx, rc in enumerate(ranges):
            if rc.lo == 0:
                lines.append(f'  %r{idx} = icmp ule i32 %val, {rc.hi}')
            else:
                lines.append(f'  %off{idx} = sub i32 %val, {rc.lo}')
                lines.append(f'  %r{idx} = icmp ule i32 %off{idx}, {rc.hi - rc.lo}')
            result_var = idx
        
        for idx, dc in enumerate(domains):
            complement = (~dc.mask) & 0xFFFFFFFF
            lines.append(f'  %dm{idx} = and i32 %val, {complement}')
            lines.append(f'  %d{idx} = icmp eq i32 %dm{idx}, 0')
        
        # AND all results together
        all_conds = [f'%r{i}' for i in range(len(ranges))] + [f'%d{i}' for i in range(len(domains))]
        if len(all_conds) == 0:
            lines.append(f'  ret i1 true')
        elif len(all_conds) == 1:
            lines.append(f'  ret i1 {all_conds[0]}')
        else:
            prev = all_conds[0]
            for i in range(1, len(all_conds)):
                lines.append(f'  %and{i} = and i1 {prev}, {all_conds[i]}')
                prev = f'%and{i}'
            lines.append(f'  ret i1 {prev}')
    
    lines.append('}')
    return '\n'.join(lines)


def emit_llvm_ir_vectorized(constraint, func_name="flux_check_batch", width=16):
    """Emit LLVM IR with explicit SIMD vectorization.
    
    Theorem 4 (DeepSeek/Qwen): SIMD evaluation produces identical results to scalar.
    Proof by induction: kand preserves mask semantics at each step.
    """
    lines = [
        f'; FLUX Vectorized Constraint → LLVM IR ({width}-wide SIMD)',
        'target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"',
        'target triple = "x86_64-pc-linux-gnu"',
        '',
        f'define <{width} x i1> @{func_name}(<{width} x i32> %val) {{',
    ]
    
    if isinstance(constraint, RangeConstraint):
        if constraint.lo == 0:
            lines.append(f'  %broadcast_hi = insertelement <{width} x i32> undef, i32 {constraint.hi}, i32 0')
            lines.append(f'  %hi = shufflevector <{width} x i32> %broadcast_hi, <{width} x i32> undef, <{width} x i32> zeroinitializer')
            lines.append(f'  %cmp = icmp ule <{width} x i32> %val, %hi')
            lines.append(f'  ret <{width} x i1> %cmp')
        else:
            lines.append(f'  %broadcast_lo = insertelement <{width} x i32> undef, i32 {constraint.lo}, i32 0')
            lines.append(f'  %lo = shufflevector <{width} x i32> %broadcast_lo, <{width} x i32> undef, <{width} x i32> zeroinitializer')
            lines.append(f'  %off = sub <{width} x i32> %val, %lo')
            lines.append(f'  %span = insertelement <{width} x i32> undef, i32 {constraint.hi - constraint.lo}, i32 0')
            lines.append(f'  %span_v = shufflevector <{width} x i32> %span, <{width} x i32> undef, <{width} x i32> zeroinitializer')
            lines.append(f'  %cmp = icmp ule <{width} x i32> %off, %span_v')
            lines.append(f'  ret <{width} x i1> %cmp')
    
    elif isinstance(constraint, AndConstraint):
        ranges = [c for c in constraint.constraints if isinstance(c, RangeConstraint)]
        results = []
        
        for idx, rc in enumerate(ranges):
            if rc.lo == 0:
                lines.append(f'  %hi{idx} = insertelement <{width} x i32> undef, i32 {rc.hi}, i32 0')
                lines.append(f'  %hi_v{idx} = shufflevector <{width} x i32> %hi{idx}, <{width} x i32> undef, <{width} x i32> zeroinitializer')
                lines.append(f'  %cmp{idx} = icmp ule <{width} x i32> %val, %hi_v{idx}')
            else:
                lines.append(f'  %lo{idx} = insertelement <{width} x i32> undef, i32 {rc.lo}, i32 0')
                lines.append(f'  %lo_v{idx} = shufflevector <{width} x i32> %lo{idx}, <{width} x i32> undef, <{width} x i32> zeroinitializer')
                lines.append(f'  %off{idx} = sub <{width} x i32> %val, %lo_v{idx}')
                lines.append(f'  %span{idx} = insertelement <{width} x i32> undef, i32 {rc.hi - rc.lo}, i32 0')
                lines.append(f'  %span_v{idx} = shufflevector <{width} x i32> %span{idx}, <{width} x i32> undef, <{width} x i32> zeroinitializer')
                lines.append(f'  %cmp{idx} = icmp ule <{width} x i32> %off{idx}, %span_v{idx}')
            results.append(f'%cmp{idx}')
        
        if len(results) == 1:
            lines.append(f'  ret <{width} x i1> {results[0]}')
        else:
            prev = results[0]
            for i in range(1, len(results)):
                lines.append(f'  %and{i} = and <{width} x i1> {prev}, {results[i]}')
                prev = f'%and{i}'
            lines.append(f'  ret <{width} x i1> {prev}')
    
    lines.append('}')
    return '\n'.join(lines)


def emit_llvm_ir_batch(func_name="flux_check_batch_c", width=16):
    """Emit the C-callable batch wrapper that processes arrays."""
    return f'''
; C-callable batch constraint check
; void flux_check_batch(const int32_t* input, int32_t* output, int64_t n)
define void @{func_name}(i32* %input, i32* %output, i64 %n) {{
entry:
  %input.addr = alloca i32*
  %output.addr = alloca i32*
  %n.addr = alloca i64
  %i = alloca i64
  store i32* %input, i32** %input.addr
  store i32* %output, i32** %output.addr
  store i64 %n, i64* %n.addr
  store i64 0, i64* %i
  br label %loop.cond

loop.cond:
  %i.val = load i64, i64* %i
  %n.val = load i64, i64* %n.addr
  %cmp = icmp slt i64 %i.val, %n.val
  br i1 %cmp, label %loop.body, label %loop.end

loop.body:
  ; This is a placeholder — the actual constraint check is inlined here
  ; by the compiler when it specializes this template for a specific constraint
  %i.val2 = load i64, i64* %i
  %in.ptr = load i32*, i32** %input.addr
  %in.gep = getelementptr i32, i32* %in.ptr, i64 %i.val2
  %val = load i32, i32* %in.gep
  
  ; CONSTRAINT CHECK PLACEHOLDER — replaced by specialization
  ; For range [0, 100]: icmp ule i32 %val, 100
  %check = icmp ule i32 %val, 100
  
  %result = zext i1 %check to i32
  %out.ptr = load i32*, i32** %output.addr
  %out.gep = getelementptr i32, i32* %out.ptr, i64 %i.val2
  store i32 %result, i32* %out.gep
  
  %i.next = add i64 %i.val2, 1
  store i64 %i.next, i64* %i
  br label %loop.cond

loop.end:
  ret void
}}
'''


# ============================================================================
# Target-specific emission
# ============================================================================

def emit_ebpf(constraint, func_name="flux_check_ebpf"):
    """Emit eBPF C code for constraint checking.
    
    eBPF = free formal verification. The kernel verifier mathematically proves:
    - No crashes (bounds checked)
    - No infinite loops (bounded iteration)
    - No OOB access (verified memory access)
    
    This is a constraint checker the Linux kernel ITSELF verifies is correct.
    """
    lines = [
        '#include <linux/bpf.h>',
        '#include <bpf/bpf_helpers.h>',
        '',
        f'SEC("socket")',
        f'int {func_name}(struct __sk_buff *skb) {{',
        '    // eBPF constraint checker',
        '    // The kernel verifier proves this program:',
        '    //   1. Terminates (bounded loop)',
        '    //   2. No OOB access (verified bounds)',
        '    //   3. No crashes (type-checked)',
        '',
        '    // Extract value from packet (example: byte at offset 0)',
        '    __u32 val;',
        '    bpf_skb_load_bytes(skb, 0, &val, sizeof(val));',
        '',
    ]
    
    if isinstance(constraint, RangeConstraint):
        if constraint.lo == 0:
            lines.append(f'    // Range [0, {constraint.hi}] → unsigned comparison')
            lines.append(f'    if (val > {constraint.hi}) return 0;  // DROP')
        else:
            lines.append(f'    // Range [{constraint.lo}, {constraint.hi}]')
            lines.append(f'    if (val < {constraint.lo} || val > {constraint.hi}) return 0;  // DROP')
    
    elif isinstance(constraint, DomainConstraint):
        complement = (~constraint.mask) & 0xFFFFFFFF
        lines.append(f'    // Domain check: (val & 0x{constraint.mask:X}) == val')
        lines.append(f'    if (val & 0x{complement:X}) return 0;  // DROP')
    
    elif isinstance(constraint, AndConstraint):
        for c in constraint.constraints:
            if isinstance(c, RangeConstraint):
                lines.append(f'    if (val < {c.lo} || val > {c.hi}) return 0;  // DROP')
            elif isinstance(c, DomainConstraint):
                complement = (~c.mask) & 0xFFFFFFFF
                lines.append(f'    if (val & 0x{complement:X}) return 0;  // DROP')
    
    lines.append('')
    lines.append('    return 1;  // PASS')
    lines.append('}')
    lines.append('')
    lines.append('char _license[] SEC("license") = "Apache-2.0";')
    return '\n'.join(lines)


def emit_wasm(constraint, func_name="flux_check_wasm"):
    """Emit WAT (WebAssembly Text) for browser-based constraint checking."""
    lines = [
        '(module',
        f'  (func ${func_name} (param i32) (result i32)',
    ]
    
    if isinstance(constraint, RangeConstraint):
        if constraint.lo == 0:
            # Strength reduction: unsigned ≤ hi
            lines.append(f'    local.get 0')
            lines.append(f'    i32.const {constraint.hi}')
            lines.append(f'    i32.le_u')
        else:
            # Subtraction trick
            lines.append(f'    local.get 0')
            lines.append(f'    i32.const {constraint.lo}')
            lines.append(f'    i32.sub')
            lines.append(f'    i32.const {constraint.hi - constraint.lo}')
            lines.append(f'    i32.le_u')
    
    elif isinstance(constraint, DomainConstraint):
        complement = (~constraint.mask) & 0xFFFFFFFF
        lines.append(f'    local.get 0')
        lines.append(f'    i32.const {complement}')
        lines.append(f'    i32.and')
        lines.append(f'    i32.eqz')
    
    elif isinstance(constraint, AndConstraint):
        ranges = [c for c in constraint.constraints if isinstance(c, RangeConstraint)]
        for i, rc in enumerate(ranges):
            if rc.lo == 0:
                lines.append(f'    local.get 0')
                lines.append(f'    i32.const {rc.hi}')
                lines.append(f'    i32.le_u')
            else:
                lines.append(f'    local.get 0')
                lines.append(f'    i32.const {rc.lo}')
                lines.append(f'    i32.sub')
                lines.append(f'    i32.const {rc.hi - rc.lo}')
                lines.append(f'    i32.le_u')
            if i > 0:
                lines.append(f'    i32.and')
    
    lines.append(f'  )')
    lines.append(f'  (export "{func_name}" (func ${func_name}))')
    lines.append(')')
    return '\n'.join(lines)


def emit_riscv(constraint, func_name="flux_check_riscv"):
    """Emit RISC-V assembly (RV32I base + Xconstr extension).
    
    Xconstr extension adds custom instructions for constraint checking:
    - CREVISE: Constraint range check (hardware instruction)
    - CMASK: Domain mask check (hardware instruction)
    """
    lines = [
        f'# FLUX Constraint → RISC-V + Xconstr',
        f'# Function: {func_name}',
        f'# Input: a0 = value to check',
        f'# Output: a0 = 1 (pass) or 0 (fail)',
        '',
        f'.globl {func_name}',
        f'{func_name}:',
    ]
    
    if isinstance(constraint, RangeConstraint):
        if constraint.lo == 0:
            # li a1, hi; sltu a0, a1, a0; xori a0, a0, 1 → 3 instructions
            if constraint.hi < 4096:
                lines.append(f'    li      a1, {constraint.hi}')
            else:
                lines.append(f'    lui     a1, %hi({constraint.hi})')
                lines.append(f'    addi    a1, a1, %lo({constraint.hi})')
            lines.append(f'    sltu    a0, a1, a0      # a0 = (hi < val) ? 1 : 0')
            lines.append(f'    xori    a0, a0, 1       # invert: a0 = (val <= hi) ? 1 : 0')
        else:
            # Subtraction trick for [lo, hi]
            lines.append(f'    addi    a0, a0, -{constraint.lo}    # a0 = val - lo')
            lines.append(f'    li      a1, {constraint.hi - constraint.lo}')
            lines.append(f'    sltu    a0, a1, a0              # (span < offset)?')
            lines.append(f'    xori    a0, a0, 1                # invert')
            # Xconstr: could be single CREVISE lo,hi instruction
    
    elif isinstance(constraint, DomainConstraint):
        complement = (~constraint.mask) & 0xFFFFFFFF
        lines.append(f'    li      a1, {complement}')
        lines.append(f'    and     a0, a0, a1       # a0 = val & ~mask')
        lines.append(f'    sltiu   a0, a0, 1        # a0 = (result == 0) ? 1 : 0')
        # Xconstr: single CMASK mask instruction
    
    lines.append(f'    ret')
    return '\n'.join(lines)


# ============================================================================
# Compiler Pipeline
# ============================================================================

class FluxLLVMCompiler:
    def __init__(self):
        self.targets = {
            'x86': self.compile_native,
            'avx512': self.compile_native,
            'wasm': self.compile_wasm,
            'ebpf': self.compile_ebpf,
            'riscv': self.compile_riscv,
            'ir': self.show_ir,
        }
    
    def compile(self, constraint_text, target='x86', vectorize=False):
        constraint = parse_guard(constraint_text)
        return self.targets[target](constraint, vectorize)
    
    def show_ir(self, constraint, vectorize=False):
        if vectorize:
            return emit_llvm_ir(constraint, vectorize=True)
        return emit_llvm_ir(constraint)
    
    def compile_native(self, constraint, vectorize=False):
        """Compile to native shared library via LLVM IR → llc → gcc."""
        ir_code = emit_llvm_ir(constraint)
        
        with tempfile.NamedTemporaryFile(suffix='.ll', mode='w', delete=False) as f:
            f.write(ir_code)
            ir_path = f.name
        
        so_path = ir_path.replace('.ll', '.so')
        
        # Try llc first (if LLVM tools available)
        try:
            result = subprocess.run(
                ['llc', '-O3', '-march=x86-64', '-mattr=+avx512f',
                 '-filetype=obj', '-o', ir_path.replace('.ll', '.o'), ir_path],
                capture_output=True, text=True
            )
        except FileNotFoundError:
            result = subprocess.CompletedProcess(args=[], returncode=1, stdout='', stderr='llc not found')
        
        if result.returncode == 0:
            # Link with gcc
            subprocess.run(
                ['gcc', '-shared', '-o', so_path, ir_path.replace('.ll', '.o')],
                capture_output=True, text=True
            )
            os.unlink(ir_path.replace('.ll', '.o'))
        else:
            # Fallback: generate C and compile with gcc
            os.unlink(ir_path)
            return self._compile_c_fallback(constraint)
        
        os.unlink(ir_path)
        return so_path
    
    def _compile_c_fallback(self, constraint):
        """Fallback: emit C with AVX-512 and compile with gcc."""
        from fluxc import emit_c_avx512  # noqa
        # Inline the fallback
        c_code = self._emit_c(constraint)
        
        with tempfile.NamedTemporaryFile(suffix='.c', mode='w', delete=False) as f:
            f.write(c_code)
            c_path = f.name
        
        so_path = c_path.replace('.c', '.so')
        result = subprocess.run(
            ['gcc', '-O3', '-march=native', '-mavx512f', '-shared', '-fPIC',
             '-o', so_path, c_path],
            capture_output=True, text=True
        )
        
        if result.returncode != 0:
            raise RuntimeError(f"Compilation failed: {result.stderr}")
        
        os.unlink(c_path)
        return so_path
    
    def _emit_c(self, constraint):
        """Emit simple C for the constraint."""
        lines = ['#include <stdint.h>', '', 'int flux_check(int32_t val) {']
        if isinstance(constraint, RangeConstraint):
            if constraint.lo == 0:
                lines.append(f'    return (uint32_t)val <= {constraint.hi};')
            else:
                lines.append(f'    uint32_t off = (uint32_t)(val - {constraint.lo});')
                lines.append(f'    return off <= (uint32_t)({constraint.hi} - {constraint.lo});')
        elif isinstance(constraint, DomainConstraint):
            complement = (~constraint.mask) & 0xFFFFFFFF
            lines.append(f'    return (val & 0x{complement:X}) == 0;')
        lines.append('}')
        return '\n'.join(lines)
    
    def compile_wasm(self, constraint, vectorize=False):
        """Compile to WebAssembly."""
        wat_code = emit_wasm(constraint)
        wat_path = tempfile.mktemp(suffix='.wat')
        wasm_path = wat_path.replace('.wat', '.wasm')
        
        with open(wat_path, 'w') as f:
            f.write(wat_code)
        
        # Try wat2wasm
        result = subprocess.run(
            ['wat2wasm', wat_path, '-o', wasm_path],
            capture_output=True, text=True
        )
        
        os.unlink(wat_path)
        if result.returncode == 0:
            return wasm_path
        else:
            return wat_code  # Return WAT source if tools not available
    
    def compile_ebpf(self, constraint, vectorize=False):
        """Emit eBPF C source (needs clang + bpftool to compile)."""
        return emit_ebpf(constraint)
    
    def compile_riscv(self, constraint, vectorize=False):
        """Emit RISC-V assembly."""
        return emit_riscv(constraint)


# ============================================================================
# CLI
# ============================================================================

def main():
    if len(sys.argv) < 2:
        print("flux_llvm_backend — FLUX → LLVM IR Compiler")
        print()
        print("Usage:")
        print("  flux_llvm_backend ir <file.guard> [--vectorize]     # Show LLVM IR")
        print("  flux_llvm_backend compile <file.guard> --target ... # Compile")
        print("  flux_llvm_backend bench <file.guard>                # Compile & benchmark")
        print("  flux_llvm_backend targets                           # List targets")
        print()
        print("Targets: x86, avx512, wasm, ebpf, riscv")
        sys.exit(1)
    
    cmd = sys.argv[1]
    
    if cmd == 'targets':
        print("Supported targets:")
        print("  x86     — Native x86-64 (via LLVM IR → llc)")
        print("  avx512  — x86-64 with AVX-512 (via LLVM IR)")
        print("  wasm    — WebAssembly (via WAT)")
        print("  ebpf    — eBPF for Linux kernel (C source)")
        print("  riscv   — RISC-V + Xconstr extension (assembly)")
        return
    
    guard_file = sys.argv[2] if len(sys.argv) > 2 else None
    target = 'x86'
    vectorize = '--vectorize' in sys.argv
    
    for i, arg in enumerate(sys.argv):
        if arg == '--target' and i+1 < len(sys.argv):
            target = sys.argv[i+1]
    
    if not guard_file:
        print("Error: specify a GUARD file")
        sys.exit(1)
    
    with open(guard_file) as f:
        constraint_text = f.read()
    
    compiler = FluxLLVMCompiler()
    
    if cmd == 'ir':
        ir = compiler.compile(constraint_text, 'ir', vectorize)
        print(ir)
    
    elif cmd == 'compile':
        result = compiler.compile(constraint_text, target, vectorize)
        if os.path.isfile(result):
            print(f"Compiled to: {result}")
        else:
            print(result)
    
    elif cmd == 'bench':
        so_path = compiler.compile(constraint_text, 'x86')
        lib = ctypes.CDLL(so_path)
        
        N = 10000000
        inputs = [random.randint(0, 200) for _ in range(N)]
        results = []
        
        # Warmup
        for v in inputs[:1000]:
            lib.flux_check(v)
        
        t0 = time.perf_counter()
        for v in inputs:
            results.append(lib.flux_check(v))
        t1 = time.perf_counter()
        
        elapsed = t1 - t0
        tps = N / elapsed
        passes = sum(results)
        
        print(f"Constraint: {parse_guard(constraint_text)}")
        print(f"Target: {target}")
        print(f"  {N:,} checks in {elapsed*1000:.2f}ms = {tps:,.0f} checks/s")
        print(f"  Per check: {elapsed*1e9/N:.2f}ns")
        print(f"  Pass rate: {passes/N*100:.1f}%")
        
        if os.path.isfile(so_path):
            os.unlink(so_path)
    
    elif cmd == 'show':
        # Show all target outputs
        constraint = parse_guard(constraint_text)
        print(f"=== Constraint: {constraint} ===\n")
        
        print("--- LLVM IR (scalar) ---")
        print(emit_llvm_ir(constraint))
        print()
        
        print("--- LLVM IR (vectorized, 16-wide) ---")
        print(emit_llvm_ir(constraint, vectorize=True))
        print()
        
        print("--- eBPF (kernel constraint checker) ---")
        print(emit_ebpf(constraint))
        print()
        
        print("--- WebAssembly (WAT) ---")
        print(emit_wasm(constraint))
        print()
        
        print("--- RISC-V + Xconstr ---")
        print(emit_riscv(constraint))

if __name__ == '__main__':
    main()
