#!/usr/bin/env python3
"""
flux_ebpf_deploy.py — FLUX eBPF Constraint Deployment Pipeline

Complete pipeline:
  1. Parse GUARD constraints → generate constraint map initialization
  2. Compile eBPF C to BPF bytecode (via clang)
  3. Generate userspace loader that sets constraints and reads stats

Usage:
    python3 flux_ebpf_deploy.py generate <file.guard> --output-dir <dir>
    python3 flux_ebpf_deploy.py compile <ebpf_c_file> --output <output.o>
    python3 flux_ebpf_deploy.py loader <file.guard> --output <loader.c>
    python3 flux_ebpf_deploy.py full <file.guard> --output-dir <dir>
"""

import sys
import os
import subprocess
import tempfile
from flux_llvm_backend import parse_guard, RangeConstraint, DomainConstraint, AndConstraint


def generate_constraint_map_init(constraint_text):
    """
    Generate C code that initializes the eBPF constraint map.
    
    Each constraint is assigned an ID and stored in the BPF map.
    The map is keyed by ID, value is {lo, hi, mask, type}.
    """
    constraint = parse_guard(constraint_text)
    
    # Flatten to list
    if isinstance(constraint, AndConstraint):
        constraints = constraint.constraints
    else:
        constraints = [constraint]
    
    lines = [
        '/*',
        ' * Constraint map initialization — generated by flux_ebpf_deploy.py',
        ' *',
        ' * Theorem 5 (Dead Elimination): redundant constraints removed',
        ' * Theorem 6 (Strength Reduction): [0, 2^k-1] ranges optimized',
        ' * Theorem 2 (Fusion): AND semantics across all constraints',
        ' */',
        '',
    ]
    
    for idx, c in enumerate(constraints):
        if isinstance(c, RangeConstraint):
            # Check for strength reduction
            if c.lo == 0 and c.hi > 0 and (c.hi + 1) & c.hi == 0:
                k = c.hi.bit_length()
                lines.append(f'/* Constraint {idx}: range [{c.lo}, {c.hi}]')
                lines.append(f' * Theorem 6: Strength reduced to mask check (2^{k}-1) */')
            else:
                lines.append(f'/* Constraint {idx}: range [{c.lo}, {c.hi}] */')
        elif isinstance(c, DomainConstraint):
            lines.append(f'/* Constraint {idx}: domain 0x{c.mask:08X} */')
    
    lines.append('')
    lines.append('struct flux_constraint {')
    lines.append('    __u32 lo;')
    lines.append('    __u32 hi;')
    lines.append('    __u32 mask;')
    lines.append('    __u32 type;  /* 0=range, 1=domain, 2=exact */')
    lines.append('};')
    lines.append('')
    
    # Generate initialization function
    lines.append('static int init_constraints(int map_fd) {')
    lines.append('    struct flux_constraint c = {};')
    lines.append('    int key;')
    lines.append('    int ret;')
    lines.append('')
    
    for idx, c in enumerate(constraints):
        lines.append(f'    /* Constraint {idx} */')
        lines.append(f'    key = {idx};')
        lines.append(f'    memset(&c, 0, sizeof(c));')
        
        if isinstance(c, RangeConstraint):
            lines.append(f'    c.lo = {c.lo};')
            lines.append(f'    c.hi = {c.hi};')
            lines.append(f'    c.type = 0;  /* range */')
        elif isinstance(c, DomainConstraint):
            lines.append(f'    c.mask = 0x{c.mask:X};')
            lines.append(f'    c.type = 1;  /* domain */')
        
        lines.append(f'    ret = bpf_map_update_elem(map_fd, &key, &c, BPF_ANY);')
        lines.append(f'    if (ret < 0) {{')
        lines.append(f'        fprintf(stderr, "Failed to set constraint {idx}: %s\\n", strerror(errno));')
        lines.append(f'        return -1;')
        lines.append(f'    }}')
        lines.append('')
    
    lines.append(f'    printf("Loaded {len(constraints)} constraints\\n");')
    lines.append('    return 0;')
    lines.append('}')
    
    return '\n'.join(lines)


def generate_userspace_loader(constraint_text):
    """
    Generate a complete userspace C loader that:
    1. Opens the eBPF object
    2. Initializes constraint map
    3. Attaches to XDP or socket
    4. Reads statistics
    """
    constraint = parse_guard(constraint_text)
    
    if isinstance(constraint, AndConstraint):
        constraints = constraint.constraints
        constraint_count = len(constraints)
    else:
        constraints = [constraint]
        constraint_count = 1
    
    lines = [
        '/*',
        ' * FLUX eBPF Userspace Loader — generated by flux_ebpf_deploy.py',
        ' *',
        ' * This loader:',
        ' *   1. Loads the eBPF constraint checker into the kernel',
        ' *   2. Initializes the constraint map with GUARD constraints',
        ' *   3. Attaches to a network interface (XDP) or socket',
        ' *   4. Reads live statistics',
        ' *',
        ' * Compile:',
        ' *   gcc -O2 -o flux_loader flux_loader.c -lbpf -lelf -lz',
        ' *',
        ' * Run:',
        ' *   sudo ./flux_loader --interface eth0 --ebpf flux_ebpf.o',
        ' */',
        '',
        '#include <stdio.h>',
        '#include <stdlib.h>',
        '#include <string.h>',
        '#include <errno.h>',
        '#include <unistd.h>',
        '#include <signal.h>',
        '#include <stdbool.h>',
        '#include <bpf/libbpf.h>',
        '#include <bpf/bpf.h>',
        '#include <net/if.h>',
        '#include <linux/if_link.h>',
        '',
        'struct flux_constraint {',
        '    __u32 lo;',
        '    __u32 hi;',
        '    __u32 mask;',
        '    __u32 type;',
        '};',
        '',
        'static volatile bool running = true;',
        '',
        'static void sig_handler(int sig) {',
        '    running = false;',
        '}',
        '',
        f'#define NUM_CONSTRAINTS {constraint_count}',
        '',
        '/*',
        ' * Initialize constraint map from compiled GUARD constraints.',
        ' * Theorem 2 (Fusion): all constraints evaluated with AND semantics.',
        ' * Theorem 5 (Dead Elimination): no redundant constraints loaded.',
        ' */',
        'static int init_constraints(int map_fd) {',
        '    struct flux_constraint c;',
        '    int key, ret;',
        '',
    ]
    
    for idx, c in enumerate(constraints):
        lines.append(f'    /* Constraint {idx} */')
        lines.append(f'    key = {idx};')
        lines.append(f'    memset(&c, 0, sizeof(c));')
        if isinstance(c, RangeConstraint):
            lines.append(f'    c.lo = {c.lo};')
            lines.append(f'    c.hi = {c.hi};')
            lines.append(f'    c.type = 0;')
            lines.append(f'    /* Range [{c.lo}, {c.hi}] */')
        elif isinstance(c, DomainConstraint):
            lines.append(f'    c.mask = 0x{c.mask:X};')
            lines.append(f'    c.type = 1;')
            lines.append(f'    /* Domain 0x{c.mask:08X} */')
        lines.append(f'    ret = bpf_map_update_elem(map_fd, &key, &c, BPF_ANY);')
        lines.append(f'    if (ret < 0) {{')
        lines.append(f'        fprintf(stderr, "Failed to set constraint {idx}\\n");')
        lines.append(f'        return -1;')
        lines.append(f'    }}')
        lines.append('')
    
    lines.append(f'    printf("Loaded %d constraints into map\\n", NUM_CONSTRAINTS);')
    lines.append('    return 0;')
    lines.append('}')
    lines.append('')
    
    # Stats reading
    lines.append('static void read_stats(int stats_fd) {')
    lines.append('    __u64 total = 0, violations = 0, passed = 0;')
    lines.append('    __u32 key;')
    lines.append('')
    lines.append('    key = 0; bpf_map_lookup_elem(stats_fd, &key, &total);')
    lines.append('    key = 1; bpf_map_lookup_elem(stats_fd, &key, &violations);')
    lines.append('    key = 2; bpf_map_lookup_elem(stats_fd, &key, &passed);')
    lines.append('')
    lines.append('    printf("Total: %llu Passed: %llu Violations: %llu "')
    lines.append('           "(%.1f%% dropped)\\n",')
    lines.append('           (unsigned long long)total, (unsigned long long)passed,')
    lines.append('           (unsigned long long)violations,')
    lines.append('           total > 0 ? 100.0 * violations / total : 0.0);')
    lines.append('')
    
    # Main
    lines.append('int main(int argc, char **argv) {')
    lines.append('    const char *ifname = "eth0";')
    lines.append('    const char *ebpf_obj = "flux_ebpf.o";')
    lines.append('    int ifindex;')
    lines.append('    struct bpf_object *obj;')
    lines.append('    struct bpf_program *prog;')
    lines.append('    int prog_fd, map_fd, stats_fd;')
    lines.append('    int ret;')
    lines.append('')
    lines.append('    /* Parse args */')
    lines.append('    for (int i = 1; i < argc; i++) {')
    lines.append('        if (strcmp(argv[i], "--interface") == 0 && i+1 < argc)')
    lines.append('            ifname = argv[++i];')
    lines.append('        else if (strcmp(argv[i], "--ebpf") == 0 && i+1 < argc)')
    lines.append('            ebpf_obj = argv[++i];')
    lines.append('    }')
    lines.append('')
    lines.append('    signal(SIGINT, sig_handler);')
    lines.append('    signal(SIGTERM, sig_handler);')
    lines.append('')
    lines.append('    /* Open and load eBPF object */')
    lines.append('    obj = bpf_object__open(ebpf_obj);')
    lines.append('    if (libbpf_get_error(obj)) {')
    lines.append('        fprintf(stderr, "Failed to open eBPF object: %s\\n", ebpf_obj);')
    lines.append('        return 1;')
    lines.append('    }')
    lines.append('')
    lines.append('    ret = bpf_object__load(obj);')
    lines.append('    if (ret) {')
    lines.append('        fprintf(stderr, "Failed to load eBPF object\\n");')
    lines.append('        return 1;')
    lines.append('    }')
    lines.append('')
    lines.append('    /* Get map FDs */')
    lines.append('    map_fd = bpf_object__find_map_fd_by_name(obj, "constraints");')
    lines.append('    stats_fd = bpf_object__find_map_fd_by_name(obj, "stats");')
    lines.append('    if (map_fd < 0 || stats_fd < 0) {')
    lines.append('        fprintf(stderr, "Failed to find eBPF maps\\n");')
    lines.append('        return 1;')
    lines.append('    }')
    lines.append('')
    lines.append('    /* Initialize constraints */')
    lines.append('    if (init_constraints(map_fd) < 0)')
    lines.append('        return 1;')
    lines.append('')
    lines.append('    /* Attach XDP program */')
    lines.append('    prog = bpf_object__find_program_by_name(obj, "flux_constraint_xdp");')
    lines.append('    if (!prog) {')
    lines.append('        fprintf(stderr, "Failed to find XDP program\\n");')
    lines.append('        return 1;')
    lines.append('    }')
    lines.append('    prog_fd = bpf_program__fd(prog);')
    lines.append('')
    lines.append('    ifindex = if_nametoindex(ifname);')
    lines.append('    if (!ifindex) {')
    lines.append('        fprintf(stderr, "Interface %s not found\\n", ifname);')
    lines.append('        return 1;')
    lines.append('    }')
    lines.append('')
    lines.append('    ret = bpf_xdp_attach(ifindex, prog_fd, XDP_FLAGS_SKB_MODE, NULL);')
    lines.append('    if (ret) {')
    lines.append('        fprintf(stderr, "Failed to attach XDP to %s: %s\\n", ifname, strerror(-ret));')
    lines.append('        return 1;')
    lines.append('    }')
    lines.append('')
    lines.append('    printf("FLUX eBPF constraint checker attached to %s\\n", ifname);')
    lines.append('    printf("Press Ctrl-C to detach and exit\\n\\n");')
    lines.append('')
    lines.append('    /* Event loop — print stats every second */')
    lines.append('    while (running) {')
    lines.append('        sleep(1);')
    lines.append('        read_stats(stats_fd);')
    lines.append('    }')
    lines.append('')
    lines.append('    /* Cleanup */')
    lines.append('    bpf_xdp_detach(ifindex, XDP_FLAGS_SKB_MODE, NULL);')
    lines.append('    printf("\\nDetached from %s\\n", ifname);')
    lines.append('')
    lines.append('    /* Final stats */')
    lines.append('    read_stats(stats_fd);')
    lines.append('')
    lines.append('    bpf_object__close(obj);')
    lines.append('    return 0;')
    lines.append('}')
    
    return '\n'.join(lines)


def compile_ebpf(ebpf_c_path, output_path=None):
    """Compile eBPF C source to BPF bytecode using clang."""
    if output_path is None:
        output_path = ebpf_c_path.replace('.c', '.o')
    
    cmd = [
        'clang',
        '-O2',
        '-target', 'bpf',
        '-c', ebpf_c_path,
        '-o', output_path,
        '-g',  # generate BTF for map introspection
        '-D__TARGET_ARCH_x86',
    ]
    
    print(f"Compiling: {' '.join(cmd)}")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except (FileNotFoundError, subprocess.TimeoutExpired) as e:
        print(f"eBPF compilation requires clang with BPF target: {e}")
        return None
    
    if result.returncode != 0:
        print(f"Compilation failed:\n{result.stderr}")
        return None
    
    print(f"Compiled: {output_path}")
    return output_path


def full_pipeline(constraint_text, output_dir):
    """Run the full eBPF deployment pipeline."""
    os.makedirs(output_dir, exist_ok=True)
    
    # 1. Generate eBPF C
    from flux_llvm_backend import emit_ebpf
    constraint = parse_guard(constraint_text)
    ebpf_c = emit_ebpf(constraint)
    
    ebpf_c_path = os.path.join(output_dir, 'flux_ebpf_generated.c')
    with open(ebpf_c_path, 'w') as f:
        f.write(ebpf_c)
    print(f"Generated eBPF C: {ebpf_c_path}")
    
    # 2. Generate constraint map init
    map_init = generate_constraint_map_init(constraint_text)
    map_init_path = os.path.join(output_dir, 'flux_constraint_init.c')
    with open(map_init_path, 'w') as f:
        f.write(map_init)
    print(f"Generated constraint init: {map_init_path}")
    
    # 3. Generate userspace loader
    loader_c = generate_userspace_loader(constraint_text)
    loader_path = os.path.join(output_dir, 'flux_loader.c')
    with open(loader_path, 'w') as f:
        f.write(loader_c)
    print(f"Generated loader: {loader_path}")
    
    # 4. Try to compile eBPF
    ebpf_o_path = os.path.join(output_dir, 'flux_ebpf.o')
    result = compile_ebpf(ebpf_c_path, ebpf_o_path)
    
    if result:
        print(f"\nDeployment ready!")
        print(f"  eBPF object: {ebpf_o_path}")
        print(f"  Loader: compile with: gcc -O2 -o flux_loader {loader_path} -lbpf -lelf -lz")
        print(f"  Deploy: sudo ./flux_loader --interface eth0 --ebpf {ebpf_o_path}")
    else:
        print(f"\neBPF compilation requires clang with BPF target.")
        print(f"  Source files generated — compile on a system with clang/bpftool.")
    
    return True


def main():
    if len(sys.argv) < 2:
        print("flux_ebpf_deploy — FLUX eBPF Deployment Pipeline")
        print()
        print("Usage:")
        print("  flux_ebpf_deploy generate <file.guard> --output-dir <dir>")
        print("  flux_ebpf_deploy compile <ebpf_c> --output <output.o>")
        print("  flux_ebpf_deploy loader <file.guard> --output <loader.c>")
        print("  flux_ebpf_deploy full <file.guard> --output-dir <dir>")
        sys.exit(1)
    
    cmd = sys.argv[1]
    
    output_dir = '.'
    output_file = None
    
    for i, arg in enumerate(sys.argv):
        if arg == '--output-dir' and i+1 < len(sys.argv):
            output_dir = sys.argv[i+1]
        if arg == '--output' and i+1 < len(sys.argv):
            output_file = sys.argv[i+1]
    
    if cmd == 'generate':
        guard_file = sys.argv[2]
        with open(guard_file) as f:
            constraint_text = f.read()
        result = generate_constraint_map_init(constraint_text)
        if output_file:
            with open(output_file, 'w') as f:
                f.write(result)
            print(f"Written to {output_file}")
        else:
            print(result)
    
    elif cmd == 'compile':
        ebpf_c = sys.argv[2]
        compile_ebpf(ebpf_c, output_file)
    
    elif cmd == 'loader':
        guard_file = sys.argv[2]
        with open(guard_file) as f:
            constraint_text = f.read()
        result = generate_userspace_loader(constraint_text)
        if output_file:
            with open(output_file, 'w') as f:
                f.write(result)
            print(f"Written to {output_file}")
        else:
            print(result)
    
    elif cmd == 'full':
        guard_file = sys.argv[2]
        with open(guard_file) as f:
            constraint_text = f.read()
        full_pipeline(constraint_text, output_dir)


if __name__ == '__main__':
    main()
